"""added added_by field

Revision ID: 0fa75e4f5f5c
Revises: 
Create Date: 2022-12-08 00:56:40.036221

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0fa75e4f5f5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=256), nullable=False),
    sa.Column('short', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_map_original'), 'url_map', ['original'], unique=False)
    op.create_index(op.f('ix_url_map_short'), 'url_map', ['short'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_map_short'), table_name='url_map')
    op.drop_index(op.f('ix_url_map_original'), table_name='url_map')
    op.drop_table('url_map')
    # ### end Alembic commands ###
